# Generated by Django 5.0 on 2024-01-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('d_rate', models.FloatField(default=0.0)),
                ('d_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='disscountProducts_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='discountProducts_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='discountProducts_images/')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
