# Generated by Django 5.0 on 2024-01-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_discountproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproduct',
            name='d_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='d_rate',
            field=models.IntegerField(default=0),
        ),
    ]
